export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Database
  DB_CONFLICT: 'PRISMA_CONFLICT',
  DB_NOT_FOUND: 'PRISMA_NOT_FOUND',
  DB_ERROR: 'PRISMA_ERROR',

  // Common
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
